# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
import numpy as np

#### 2. Print your NumPy version.

In [9]:
print(np.version.version)

1.20.3


#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [11]:
a = np.random.random([2,3,5])
a

array([[[0.88104707, 0.99831038, 0.91537442, 0.03203262, 0.71323652],
        [0.04894458, 0.3154229 , 0.42744705, 0.6298316 , 0.65050335],
        [0.97259751, 0.13893   , 0.68252739, 0.12915054, 0.88433835]],

       [[0.28877155, 0.06037248, 0.15826125, 0.13172172, 0.13220182],
        [0.6506599 , 0.54044683, 0.17327044, 0.39835188, 0.73965404],
        [0.61578918, 0.67709251, 0.81480956, 0.50359439, 0.63885121]]])

In [13]:
a = np.random.randn(2,3,5)
a

array([[[ 1.38643817,  1.53841135,  0.25618518,  0.28324832,
          0.07866264],
        [-1.6701377 ,  0.42868629,  2.20056149,  0.20994526,
          0.79046517],
        [ 0.7191191 , -0.17494959, -1.49843098,  0.71870632,
         -1.17671397]],

       [[-1.61518553,  0.87975136, -1.30102304, -2.89143613,
          0.33621296],
        [ 1.73905866, -0.27823488,  0.58971142,  0.52670258,
         -0.54244413],
        [-0.71460933,  0.66264096, -0.81057052, -0.65354233,
         -0.22938808]]])

In [15]:
low = 0
high = 100
shape = (2,3,5)

a = np.random.randint(low,high,shape)
a

array([[[96, 82, 75, 27, 81],
        [76,  4, 29, 11, 32],
        [86, 15, 88,  6, 16]],

       [[54, 62, 77, 19, 88],
        [98, 20, 64, 40, 68],
        [14, 76, 59, 26, 20]]])

#### 4. Print *a*.


In [17]:
print(a)

[[[96 82 75 27 81]
  [76  4 29 11 32]
  [86 15 88  6 16]]

 [[54 62 77 19 88]
  [98 20 64 40 68]
  [14 76 59 26 20]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [18]:
shape = (5,2,3)
fill_value = 1

b = np.full(shape, fill_value)

#### 6. Print *b*.


In [19]:
print(b)

[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [20]:
a.size == b.size
# True

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [23]:
a + b # np.add(a, b)
# Not possible as shapes are different

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [27]:
c = np.transpose(b, (1,2,0))

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [35]:
d = a + c
# Works have a and c have same shape

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [36]:
print(f"a:\n{a}")
print(f"d:\n{d}")

# d's values are equal to a's values + 1
# Matrix addition of a and c, and c only had values of 1

a:
[[[96 82 75 27 81]
  [76  4 29 11 32]
  [86 15 88  6 16]]

 [[54 62 77 19 88]
  [98 20 64 40 68]
  [14 76 59 26 20]]]
d:
[[[97 83 76 28 82]
  [77  5 30 12 33]
  [87 16 89  7 17]]

 [[55 63 78 20 89]
  [99 21 65 41 69]
  [15 77 60 27 21]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [49]:
e = a * c

#### 13. Does *e* equal to *a*? Why or why not?


In [50]:
e == a
# e equals to a, as we have done a multiplication element by element)

array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [54]:
d_max = d.max()
print(d_max)

d_min = d.min()
print(d_min)

d_mean = d.mean()
print(d_mean)

99
5
51.3


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [56]:
f = np.empty((2,3,5))
f

array([[[4.74e-322, 4.05e-322, 3.71e-322, 1.33e-322, 4.00e-322],
        [3.75e-322, 1.98e-323, 1.43e-322, 5.43e-323, 1.58e-322],
        [4.25e-322, 7.41e-323, 4.35e-322, 2.96e-323, 7.91e-323]],

       [[2.67e-322, 3.06e-322, 3.80e-322, 9.39e-323, 4.35e-322],
        [4.84e-322, 9.88e-323, 3.16e-322, 1.98e-322, 3.36e-322],
        [6.92e-323, 3.75e-322, 2.91e-322, 1.28e-322, 9.88e-323]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [68]:
for x in range(d.shape[0]):
    for y in range(d.shape[1]):
        for z in range(d.shape[2]):
            if d[x,y,z] == d_min:
                f[x,y,z] = 0
            elif d[x,y,z] > d_min and d[x,y,z] < d_mean:
                f[x,y,z] = 25
            elif d[x,y,z] == d_mean:
                f[x,y,z] = 50
            elif d[x,y,z] > d_mean and d[x,y,z] < d_max:
                f[x,y,z] = 75
            elif d[x,y,z] == d_max:
                f[x,y,z] = 100
            else:
                print("error...")

#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [67]:
print(d)
print()
print(f)

# f is as expected

[[[97 83 76 28 82]
  [77  5 30 12 33]
  [87 16 89  7 17]]

 [[55 63 78 20 89]
  [99 21 65 41 69]
  [15 77 60 27 21]]]

[[[ 75.  75.  75.  25.  75.]
  [ 75.   0.  25.  25.  25.]
  [ 75.  25.  75.  25.  25.]]

 [[ 75.  75.  75.  25.  75.]
  [100.  25.  75.  25.  75.]
  [ 25.  75.  75.  25.  25.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [71]:
f = f.astype(str) # need to change the datatype to string

for x in range(d.shape[0]):
    for y in range(d.shape[1]):
        for z in range(d.shape[2]):
            if d[x,y,z] == d_min:
                f[x,y,z] = "E"
            elif d[x,y,z] > d_min and d[x,y,z] < d_mean:
                f[x,y,z] = "D"
            elif d[x,y,z] == d_mean:
                f[x,y,z] = "C"
            elif d[x,y,z] > d_mean and d[x,y,z] < d_max:
                f[x,y,z] = "B"
            elif d[x,y,z] == d_max:
                f[x,y,z] = "A"
            else:
                print("error...")
                
print(f)

[[['B' 'B' 'B' 'D' 'B']
  ['B' 'E' 'D' 'D' 'D']
  ['B' 'D' 'B' 'D' 'D']]

 [['B' 'B' 'B' 'D' 'B']
  ['A' 'D' 'B' 'D' 'B']
  ['D' 'B' 'B' 'D' 'D']]]
